<!DOCTYPE html>

<html>

<?php
    $scriptList = array('JS/jquery-1.11.3.min.js', 'JS/carousel.js');
    $currentPage = 'index.php';
    include('header.php');
?>

    <div id="main">
        <p>
            Welcome to Classic Cinema, your online store for classic film.
        </p>
        <div id="carousel">
            <!-- Content generated by JavaScript in carousel.js -->
        </div>
    </div>

    <?php include ("footer.php"); ?>

        </body>

</html>